---

# VPC
- name:               Create VPC
  ec2_vpc_net:
    name:             "{{ vpc_name }}"
    cidr_block:       "{{ vpc_cidr_block }}"
    region:           "{{ aws_region }}"
    profile:          "{{ aws_profile }}"
    dns_hostnames:    "yes"
    state:            "present"
  register: my_vpc

- name:               Set VPC ID in variable
  set_fact:
    vpc_id:           "{{ my_vpc.vpc.id }}"

- debug: var=vpc_id

# Subnets
- name:               Create Public Subnet [AZ1]
  ec2_vpc_subnet:
    vpc_id:           "{{ vpc_id }}"
    cidr:             "{{ public_subnet_az1_cidr }}"
    az:               "{{ aws_region }}{{ vpc_az1_letter }}"
    region:           "{{ aws_region }}"
    profile:          "{{ aws_profile }}"
    resource_tags:
      Name:           "{{ vpc_name }} Public Subnet"
    state:            "present"
  register: my_public_subnet_az1

- name:               Set Public Subnet ID in variable [AZ1]
  set_fact:
    public_subnet_az1_id: "{{ my_public_subnet_az1.subnet.id }}"

- debug: var=public_subnet_az1_id

# Internet Gateway
- name:               Create Internet Gateway for VPC
  ec2_vpc_igw:
    #name:             "{{ vpc_name }}"     # Not Supported
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    profile:          "{{ aws_profile }}"
    state:            "present"
  register: my_vpc_igw

- name:               Set Internet Gateway ID in variable
  set_fact:
    igw_id:           "{{ my_vpc_igw.gateway_id }}"

- name:               Create Elastic IP [AZ1]
  ec2_eip:
    region:           "{{ aws_region }}"
    profile:          "{{ aws_profile }}"
    in_vpc:           yes
    state:            "present"
  register: eip_az1

- debug: var=eip_az1.allocation_id

- name:               Set Elastic IP in variable [AZ1]
  set_fact:
    my_elastic_az1_ip:    "{{ eip_az1.allocation_id }}"

# Subnet Routes
- name:               Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    profile:          "{{ aws_profile }}"
    tags:
      Name:           "{{ vpc_name }} Public"
    subnets:
      - "{{ public_subnet_az1_id }}"
    routes:
      - dest:         "0.0.0.0/0"
        gateway_id:   "{{ igw_id }}"

# Firewalls
- name:               Set up Network ACLs
  ec2_vpc_nacl:
    name:             "{{ vpc_name }} Public"
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    profile:          "{{ aws_profile }}"
    subnets:
      - "{{ public_subnet_az1_id }}"
    tags:
      Name:           "{{ vpc_name }} Public"
    ingress: [
      [100, 'tcp', 'allow', '0.0.0.0/0', null, null, 80, 80],
      [101, 'tcp', 'allow', '0.0.0.0/0', null, null, 443, 443],
      [103, 'icmp', 'allow', '0.0.0.0/0', -1, -1],
      [122, 'tcp', 'allow', '0.0.0.0/0', null, null, 22, 22],
      [153, 'udp', 'allow', '0.0.0.0/0', null, null, 53, 53],
      [887, 'tcp', 'allow', '0.0.0.0/0', null, null, 1024, 65535],
      [888, 'udp', 'allow', '0.0.0.0/0', null, null, 1024, 65535]
    ]
    egress: [
      [100, 'tcp', 'allow', '0.0.0.0/0', null, null, 80, 80],
      [101, 'tcp', 'allow', '0.0.0.0/0', null, null, 443, 443],
      [103, 'icmp', 'allow', '0.0.0.0/0', -1, -1],
      [122, 'tcp', 'allow', '0.0.0.0/0', null, null, 22, 22],
      [153, 'udp', 'allow', '0.0.0.0/0', null, null, 53, 53],
      [887, 'tcp', 'allow', '0.0.0.0/0', null, null, 1024, 65535]
    ]
    state:            "present"
