---

- hosts: remote
  user: ubuntu
  become: yes
  become_user: root
  vars:
    php_memory_limit:  '128M'
    node_version: "9.11.2"
    repository: "git@github.com:Manhatech/ev_shopper"
    clone_dir: /tmp/clone
    deploy_private_key: "-----BEGIN RSA PRIVATE KEY-----
MIIJKQIBAAKCAgEAx/FJyOsTJ9f7VSjx52xBMSyhAggen+B4Z3V+pmW7Pyn1eXvW
5bteFMp4ZOfv3syFC8k4XXnBTaL3uZO9CsSa4tipb35V3N1KtCAySBNJmUK0RRdp
n4CI7Gw2cHn7gEgG+zq4P+J+gdY5AouUjg8kZZazezwHI/ipMkVGMV+3QdtvZIl4
6D3g6i1OfYqogE0OiAR0sFDUiGBx6dFgymhU0bIHxXdVTouguvJKBEud7uu6ixjr
D4/KJGNv2W9x49TiYuChBv8KvSDWaVhB/Ks/Ns7LVwByosW+K31X4ODiadHbs3MN
+TC+53fWIrVPBzZvMA0GQnipeiMOF19OU0EUKJy4V4zkteDbI+pt/O9f8L0DlNJ2
1n5C8NV+XjraIf52tvW+QfjIj2iAkKt4Ghtc28Blme4xw1WlIogpHaxNeQ3qfd+u
BX0+D74XxAOIlPDlBZj7Ca3U5OWv47EtGnmnhJNJTcdsp1PpR6leyZtNzXj5IXRE
N8QPF9Jm3JFFeDQlaMC4DetdhTcwM5dAFSF9wJBJ2OnEXnsAyIgUAuT/vo0SmA6a
ybBEHO+S9ONDqZSoYYTOglKDZCAkgw+W6hzwugN3nXt5vy6stSXaDhfoHuSjsrx+
2qwqwGylAH/gmY067UKQgme9i8CMqd3FdQuqhLRV6BlMP7WhqbFO0mZg/OkCAwEA
AQKCAgEAkc1rv/9knaaLmiNcnCU+OQzRcLjZFD9NrixpKhB/hmUjo+5h3G9RARpQ
x0y3iCJeVyTqXIgAJYxU19hbf7G1PP1AOZTIKmKZKldcM2EVR5Tz/no/RNgngTi8
TjM16usbZDMCz1tsY2QDeM6uixWRth86TQCOOHYJdCY+NJ0W9wh857S0Ha+aB0r4
tOXbUIxgr2GIclbPVY/3IcnUqmWAjNYlgqMt6zQ5BnrO7Ojzh5oRE4QdTeDOSNDW
bJovVDQWzoH+CysK+rYqhPGeVRHP7DjK4WvrLLXEotQptExp7z7g1rBtHS2l2Qdz
eSX8NkdEt6aXzPtOo0lS6kpOxLltZ5HunQ+/XFS1DyfnxB+yCUzvdl0GWot1ypBR
UgW5JTosyCxfYm0VufxwlcDevylTN4hjs0tNU1oahg5JY58ZYmpIQXK7x3sW2ICz
wuJ533c1yP80wkSkVdgAE8ugq5tnlpwqjkFNE2MaUzKbQPXYNigZg02bQBtQvfx8
lQ5Th6kEF/hiwK1DuvPKHtiOY0Qb1FiGLaz+BtsDoCYcjIGum4NvMy+n7hnWGcgw
DGbqs7DEYUjPXxj12CcIwpsa9zpH9sWfhQqanPq5+ufQpvR8fb9SrPpG5R+9ZQ9a
j/dUHyqD8PkDGGULF9g7B6mvM6jdubSDa6omdMKidTfYdFzZnT0CggEBAOyJx1vg
IEBRjpT9HOM1vASRVbSyV4u80ME/AhRX2ax1fgoOiK6N4mrxJ0s0rP5MqdviXmen
PEuWMYg3Ao1rFHnWlUoygfEFMyyaq7HWReWc8C8kQB36xEAg998aGstgXp1pnHiX
9ZR1Cq965QYBQ4DxE0RKXq/wyX/d4tehRUSIYDIpKIcpzle39Zb+GIFUvYhUbZeM
cwBmxyUqj84yU93/AscRBwo7jAUFYAlCa72A0YjPAFxwshRqrAuGshtIIXK19V6L
ebRTBZWbHq2JiBkXJr0XN6Wn5AEGTuzPPLnfffa79hPaw/ky8yln0aGKlPRY0btB
VxOdxVJiJZ3NqssCggEBANhksTq6LhqecWFLravJexXv8bs9HTHZORa3sKmECi0Q
siQWytSbXk4+lYBxiUHMFJVGlK6GdrGe4RjNt/odwKqgLe0HzFcOOCzINq9LcJkE
cwrgpByDv7M7+BVk6VfWJOgQPjtMdyqgUQbGob4Hs1Yv7ECZnf3bX3ZlE98aTBlA
hMfRJZihe1dz/FBlv7JD45zGRjLYmVQ5Un4wi4/5iHo2kyizAKczO+Cz/EtO7Qhj
H3IBz7+yqoU1xKHug02+Vp3TPTGHaOTysgB4XXu9HeFai9T1mMe0+p4BsvOkfGOU
SEdQcglVq6pNTYnxGDST2f1sZzI9lqoxkw4cQcsZPJsCggEBAM3S2gGtVgMBtMMa
OL/Q6ylCWcShhyJWC4SMUj/nbcbued1AZlkVp1aNPzbmwD2L8iYepS0mzYWsTK+N
xo/OBIQ8X62vo3hZoP0IHazimfHCDRHIRm6P3aM7zNR6v6QG2G27D2e0OwKSkdi+
ZHlEMjwKCkzbNed866lzJ0eg0khfLu2W+OgcTavwrChWNHadiUsOxEoh8ZQA2vsR
PQ8cpfO/Seh0fZ6+0Akycy27eUrtw+Z60YKeoaa4Z7qj22l363sIsFkznpR1xZ83
2osA6MeEaLYTdN2V6QWnOpg/gETxH4fKaMdADlVSq1p1N2mM0C6K9v0tTxsHp0MX
mknlQ98CggEAdrEMUSUL4sfjcrWa5e4WmFrLIaOM3unCGYbZ3LEzD7Lns0nZKTKr
UImdYR1lZvS0mYhkRzIz6os19m/oKMWnBy/i4O91Eo8XGuEatZ3Qfe3l2CKNgaJ2
RK5xDfMS1n38MlmueMIhXv0eVHQhBWWd5XlVwb1A3pw0SXF5q9b1xKgR7LP4RjbU
u4w/6i1VL0dzkmti18Lcn0jtyY+BDZCWXkqO/zTn983vWvn+OaRp+T69YcBCnmg2
heiPGS8FUGBFjD3wg7k9PM8t+XoL9LIvsIsExeOMUIYhLQfLiz4+iDQuTQd/9UTL
axcJn87hMv2iBRIvrGwBtwqIGaZAJFGMXwKCAQAbcs4BfS8DiaVJJ92FY2AZLhNj
mryC2RGcAC3A1FpMM5WGYECkt/sckSmr/y5EnywsNtNrAK5rZGuKhghzuGie2BsT
B6nwrKMJquNdL779zCo38/TFk33UM33USXWtcGU/2nyT3Wwn7cIHjCX8JQN8ckPJ
HQTwnGP6ATm55woWDP4f1+Nnrh1YLI+frzz8LMtw4koQQaz5oUJ+Y1nNgx64nMOB
pm0gx8jnipITDA/zZzs8nWQYo+OdPk6dQc3431qJNOFlzohYYiGYiEs9fng7sS6W
d8H9YXDjNRGH0PuP0xhELH6/H3e2AMdvzvPTEYBN6rFHhtp2yWnYGnihEcO5
-----END RSA PRIVATE KEY-----
"
  roles:
    - aws.ec2.laravel
    - deploy
