---

# product-code from https://wiki.centos.org/Cloud/AWS
- name:               Get AMI for Ubuntu in region
  ec2_ami_facts:
    region:           "{{ aws_region }}"
    profile:          "{{ aws_profile }}"
    owners:           "aws-marketplace"
    filters:
      name: "ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"
  no_result_action: fail
  register: amis

# - debug: var="{{ amis.images | sort(attribute='creation_date') | last }}"

- name:               Set AMI ID in variable
  set_fact:
    latest_ami:           "{{ amis.images | sort(attribute='creation_date') | last }}"

- name:               Create Web App Security Group
  ec2_group:
    name:             "Web App"
    #tags:                              # Not Supported
    #  Name: "name"
    description:      "Port 80, 443, 22 from Bastion"
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    profile:          "{{ aws_profile }}"
    rules:
      - proto:        tcp
        from_port:    80
        to_port:      80
        cidr_ip:      0.0.0.0/0
      - proto:        tcp
        from_port:    443
        to_port:      443
        cidr_ip:      0.0.0.0/0
      - proto:        tcp
        from_port:    22
        to_port:      22
        group_id:      "{{ bastion_group_id }}"
      - proto:        icmp
        from_port:    -1
        to_port:      -1
        group_id:      "{{ bastion_group_id }}"
    state:            "present"
  register: my_webapp_group

- name:               Set Web App Security Group ID in variable
  set_fact:
    webapp_group_id: "{{ my_webapp_group.group_id }}"

- name:               Create Web App Server [AZ1]
  ec2:
    profile:          "{{ aws_profile }}"
    key_name:         "{{ aws_key_name }}"
    instance_type:    "{{ docker_instance_type }}"
    image:            "{{ latest_ami.image_id }}"
    region:           "{{ aws_region }}"
# simplify by adding to public subnet
    vpc_subnet_id:    "{{ public_subnet_az1_id }}"
    #volumes:
    #  - device_name: /dev/sda1
    #    volume_type: gp2
    #    volume_size: 8
    #    encrypted: true
    #    delete_on_termination: true
    wait:             yes
    group_id:         ["{{ webapp_group_id }}"]
    exact_count:      1
    count_tag:        "webapp_az1"
    instance_tags:
      Name:           "{{vpc_name}} Web App"
      webapp_az1:     "true"
  register: webapp_az1_ec2s
